// Generated by CoffeeScript 1.3.3
(function() {
  var app, express, port, routes;

  express = require('express');

  routes = require('./routes');

  app = express.createServer();

  app.configure(function() {
    app.set('views', __dirname + '/views');
    app.set('view engine', 'jade');
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(app.router);
    return app.use(express["static"](__dirname + '/public'));
  });

  port = process.env.PORT || 3000;

  app.get('/', routes.index);

  app.get('/employees', routes.getEmployees);

  app.get('/employee/:id', routes.getEmployee);

  app.listen(port, function() {
    return console.log("Express server listening on port %d in %s mode", app.address().port, app.settings.env);
  });

}).call(this);
