// Generated by CoffeeScript 1.3.3
(function() {
  var Employee, employee, employee1, employee2;

  Employee = (function() {

    Employee.list = [];

    Employee.counter = 0;

    function Employee(name, forname, picture, manager) {
      this.name = name;
      this.forname = forname;
      this.picture = picture != null ? picture : 'null';
      this.manager = manager != null ? manager : 'null';
      this.id = null;
    }

    Employee.findAll = function() {
      return this.list;
    };

    Employee.prototype.save = function(callback) {
      if (!this.id) {
        Employee.counter++;
        this.id = Employee.counter;
        Employee.list.push(this);
      }
      return callback(this);
    };

    Employee.findById = function(idl) {
      var employee, result;
      result = (function() {
        var _i, _len, _ref, _results;
        _ref = this.list;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          employee = _ref[_i];
          if (employee.id === parseInt(idl)) {
            _results.push(employee);
          }
        }
        return _results;
      }).call(this);
      return result[0];
    };

    return Employee;

  })();

  employee = new Employee("Florian", "Fesseler");

  employee1 = new Employee("Florian1", "Fesseler");

  employee2 = new Employee("Florian2", "Fesseler");

  employee.save(function(m) {
    return console.log(m);
  });

  employee1.save(function(m) {
    return console.log(m);
  });

  employee2.save(function(m) {
    return console.log(m);
  });

  exports.Employee = Employee;

}).call(this);
